/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as EditPoliciesIndexImport } from './routes/edit-policies/index'
import { Route as EditPoliciesEditBeneficiariesIndexImport } from './routes/edit-policies/edit-beneficiaries/index'
import { Route as EditPoliciesEditBeneficiariesLayoutImport } from './routes/edit-policies/edit-beneficiaries/_layout'
import { Route as EditPoliciesEditBeneficiariesPolicynumberIndexImport } from './routes/edit-policies/edit-beneficiaries/$policy_number/index'
import { Route as EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexImport } from './routes/edit-policies/edit-beneficiaries/$policy_number/modify_policy/index'
import { Route as EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitImport } from './routes/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
import { Route as EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsImport } from './routes/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'

// Create Virtual Routes

const EditPoliciesEditBeneficiariesImport = createFileRoute(
  '/edit-policies/edit-beneficiaries',
)()

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EditPoliciesEditBeneficiariesRoute =
  EditPoliciesEditBeneficiariesImport.update({
    id: '/edit-policies/edit-beneficiaries',
    path: '/edit-policies/edit-beneficiaries',
    getParentRoute: () => rootRoute,
  } as any)

const EditPoliciesIndexRoute = EditPoliciesIndexImport.update({
  id: '/edit-policies/',
  path: '/edit-policies/',
  getParentRoute: () => rootRoute,
} as any)

const EditPoliciesEditBeneficiariesIndexRoute =
  EditPoliciesEditBeneficiariesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EditPoliciesEditBeneficiariesRoute,
  } as any)

const EditPoliciesEditBeneficiariesLayoutRoute =
  EditPoliciesEditBeneficiariesLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => EditPoliciesEditBeneficiariesRoute,
  } as any)

const EditPoliciesEditBeneficiariesPolicynumberIndexRoute =
  EditPoliciesEditBeneficiariesPolicynumberIndexImport.update({
    id: '/$policy_number/',
    path: '/$policy_number/',
    getParentRoute: () => EditPoliciesEditBeneficiariesRoute,
  } as any)

const EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute =
  EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexImport.update({
    id: '/$policy_number/modify_policy/',
    path: '/$policy_number/modify_policy/',
    getParentRoute: () => EditPoliciesEditBeneficiariesRoute,
  } as any)

const EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute =
  EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitImport.update(
    {
      id: '/$policy_number/modify_policy/verify-and-submit',
      path: '/$policy_number/modify_policy/verify-and-submit',
      getParentRoute: () => EditPoliciesEditBeneficiariesRoute,
    } as any,
  )

const EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute =
  EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsImport.update(
    {
      id: '/$policy_number/modify_policy/allocations',
      path: '/$policy_number/modify_policy/allocations',
      getParentRoute: () => EditPoliciesEditBeneficiariesRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/edit-policies/': {
      id: '/edit-policies/'
      path: '/edit-policies'
      fullPath: '/edit-policies'
      preLoaderRoute: typeof EditPoliciesIndexImport
      parentRoute: typeof rootRoute
    }
    '/edit-policies/edit-beneficiaries': {
      id: '/edit-policies/edit-beneficiaries'
      path: '/edit-policies/edit-beneficiaries'
      fullPath: '/edit-policies/edit-beneficiaries'
      preLoaderRoute: typeof EditPoliciesEditBeneficiariesImport
      parentRoute: typeof rootRoute
    }
    '/edit-policies/edit-beneficiaries/_layout': {
      id: '/edit-policies/edit-beneficiaries/_layout'
      path: '/edit-policies/edit-beneficiaries'
      fullPath: '/edit-policies/edit-beneficiaries'
      preLoaderRoute: typeof EditPoliciesEditBeneficiariesLayoutImport
      parentRoute: typeof EditPoliciesEditBeneficiariesRoute
    }
    '/edit-policies/edit-beneficiaries/': {
      id: '/edit-policies/edit-beneficiaries/'
      path: '/'
      fullPath: '/edit-policies/edit-beneficiaries/'
      preLoaderRoute: typeof EditPoliciesEditBeneficiariesIndexImport
      parentRoute: typeof EditPoliciesEditBeneficiariesImport
    }
    '/edit-policies/edit-beneficiaries/$policy_number/': {
      id: '/edit-policies/edit-beneficiaries/$policy_number/'
      path: '/$policy_number'
      fullPath: '/edit-policies/edit-beneficiaries/$policy_number'
      preLoaderRoute: typeof EditPoliciesEditBeneficiariesPolicynumberIndexImport
      parentRoute: typeof EditPoliciesEditBeneficiariesImport
    }
    '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations': {
      id: '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'
      path: '/$policy_number/modify_policy/allocations'
      fullPath: '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'
      preLoaderRoute: typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsImport
      parentRoute: typeof EditPoliciesEditBeneficiariesImport
    }
    '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit': {
      id: '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
      path: '/$policy_number/modify_policy/verify-and-submit'
      fullPath: '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
      preLoaderRoute: typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitImport
      parentRoute: typeof EditPoliciesEditBeneficiariesImport
    }
    '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/': {
      id: '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/'
      path: '/$policy_number/modify_policy'
      fullPath: '/edit-policies/edit-beneficiaries/$policy_number/modify_policy'
      preLoaderRoute: typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexImport
      parentRoute: typeof EditPoliciesEditBeneficiariesImport
    }
  }
}

// Create and export the route tree

interface EditPoliciesEditBeneficiariesRouteChildren {
  EditPoliciesEditBeneficiariesLayoutRoute: typeof EditPoliciesEditBeneficiariesLayoutRoute
  EditPoliciesEditBeneficiariesIndexRoute: typeof EditPoliciesEditBeneficiariesIndexRoute
  EditPoliciesEditBeneficiariesPolicynumberIndexRoute: typeof EditPoliciesEditBeneficiariesPolicynumberIndexRoute
  EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute: typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute
  EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute: typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute
  EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute: typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute
}

const EditPoliciesEditBeneficiariesRouteChildren: EditPoliciesEditBeneficiariesRouteChildren =
  {
    EditPoliciesEditBeneficiariesLayoutRoute:
      EditPoliciesEditBeneficiariesLayoutRoute,
    EditPoliciesEditBeneficiariesIndexRoute:
      EditPoliciesEditBeneficiariesIndexRoute,
    EditPoliciesEditBeneficiariesPolicynumberIndexRoute:
      EditPoliciesEditBeneficiariesPolicynumberIndexRoute,
    EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute:
      EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute,
    EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute:
      EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute,
    EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute:
      EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute,
  }

const EditPoliciesEditBeneficiariesRouteWithChildren =
  EditPoliciesEditBeneficiariesRoute._addFileChildren(
    EditPoliciesEditBeneficiariesRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/edit-policies': typeof EditPoliciesIndexRoute
  '/edit-policies/edit-beneficiaries': typeof EditPoliciesEditBeneficiariesLayoutRoute
  '/edit-policies/edit-beneficiaries/': typeof EditPoliciesEditBeneficiariesIndexRoute
  '/edit-policies/edit-beneficiaries/$policy_number': typeof EditPoliciesEditBeneficiariesPolicynumberIndexRoute
  '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations': typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute
  '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit': typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute
  '/edit-policies/edit-beneficiaries/$policy_number/modify_policy': typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/edit-policies': typeof EditPoliciesIndexRoute
  '/edit-policies/edit-beneficiaries': typeof EditPoliciesEditBeneficiariesIndexRoute
  '/edit-policies/edit-beneficiaries/$policy_number': typeof EditPoliciesEditBeneficiariesPolicynumberIndexRoute
  '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations': typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute
  '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit': typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute
  '/edit-policies/edit-beneficiaries/$policy_number/modify_policy': typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/edit-policies/': typeof EditPoliciesIndexRoute
  '/edit-policies/edit-beneficiaries': typeof EditPoliciesEditBeneficiariesRouteWithChildren
  '/edit-policies/edit-beneficiaries/_layout': typeof EditPoliciesEditBeneficiariesLayoutRoute
  '/edit-policies/edit-beneficiaries/': typeof EditPoliciesEditBeneficiariesIndexRoute
  '/edit-policies/edit-beneficiaries/$policy_number/': typeof EditPoliciesEditBeneficiariesPolicynumberIndexRoute
  '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations': typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute
  '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit': typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute
  '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/': typeof EditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/edit-policies'
    | '/edit-policies/edit-beneficiaries'
    | '/edit-policies/edit-beneficiaries/'
    | '/edit-policies/edit-beneficiaries/$policy_number'
    | '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'
    | '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
    | '/edit-policies/edit-beneficiaries/$policy_number/modify_policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/edit-policies'
    | '/edit-policies/edit-beneficiaries'
    | '/edit-policies/edit-beneficiaries/$policy_number'
    | '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'
    | '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
    | '/edit-policies/edit-beneficiaries/$policy_number/modify_policy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/edit-policies/'
    | '/edit-policies/edit-beneficiaries'
    | '/edit-policies/edit-beneficiaries/_layout'
    | '/edit-policies/edit-beneficiaries/'
    | '/edit-policies/edit-beneficiaries/$policy_number/'
    | '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'
    | '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
    | '/edit-policies/edit-beneficiaries/$policy_number/modify_policy/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EditPoliciesIndexRoute: typeof EditPoliciesIndexRoute
  EditPoliciesEditBeneficiariesRoute: typeof EditPoliciesEditBeneficiariesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EditPoliciesIndexRoute: EditPoliciesIndexRoute,
  EditPoliciesEditBeneficiariesRoute:
    EditPoliciesEditBeneficiariesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/edit-policies/",
        "/edit-policies/edit-beneficiaries"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/edit-policies/": {
      "filePath": "edit-policies/index.tsx"
    },
    "/edit-policies/edit-beneficiaries": {
      "filePath": "edit-policies/edit-beneficiaries",
      "children": [
        "/edit-policies/edit-beneficiaries/_layout",
        "/edit-policies/edit-beneficiaries/",
        "/edit-policies/edit-beneficiaries/$policy_number/",
        "/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations",
        "/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit",
        "/edit-policies/edit-beneficiaries/$policy_number/modify_policy/"
      ]
    },
    "/edit-policies/edit-beneficiaries/_layout": {
      "filePath": "edit-policies/edit-beneficiaries/_layout.tsx",
      "parent": "/edit-policies/edit-beneficiaries"
    },
    "/edit-policies/edit-beneficiaries/": {
      "filePath": "edit-policies/edit-beneficiaries/index.tsx",
      "parent": "/edit-policies/edit-beneficiaries"
    },
    "/edit-policies/edit-beneficiaries/$policy_number/": {
      "filePath": "edit-policies/edit-beneficiaries/$policy_number/index.tsx",
      "parent": "/edit-policies/edit-beneficiaries"
    },
    "/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations": {
      "filePath": "edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations.tsx",
      "parent": "/edit-policies/edit-beneficiaries"
    },
    "/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit": {
      "filePath": "edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit.tsx",
      "parent": "/edit-policies/edit-beneficiaries"
    },
    "/edit-policies/edit-beneficiaries/$policy_number/modify_policy/": {
      "filePath": "edit-policies/edit-beneficiaries/$policy_number/modify_policy/index.tsx",
      "parent": "/edit-policies/edit-beneficiaries"
    }
  }
}
ROUTE_MANIFEST_END */
