/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as EditPoliciesIndexImport } from './routes/edit-policies/index'
import { Route as EditPoliciesEditBeneficiariesImport } from './routes/edit-policies/edit-beneficiaries'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EditPoliciesIndexRoute = EditPoliciesIndexImport.update({
  id: '/edit-policies/',
  path: '/edit-policies/',
  getParentRoute: () => rootRoute,
} as any)

const EditPoliciesEditBeneficiariesRoute =
  EditPoliciesEditBeneficiariesImport.update({
    id: '/edit-policies/edit-beneficiaries',
    path: '/edit-policies/edit-beneficiaries',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/edit-policies/edit-beneficiaries': {
      id: '/edit-policies/edit-beneficiaries'
      path: '/edit-policies/edit-beneficiaries'
      fullPath: '/edit-policies/edit-beneficiaries'
      preLoaderRoute: typeof EditPoliciesEditBeneficiariesImport
      parentRoute: typeof rootRoute
    }
    '/edit-policies/': {
      id: '/edit-policies/'
      path: '/edit-policies'
      fullPath: '/edit-policies'
      preLoaderRoute: typeof EditPoliciesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/edit-policies/edit-beneficiaries': typeof EditPoliciesEditBeneficiariesRoute
  '/edit-policies': typeof EditPoliciesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/edit-policies/edit-beneficiaries': typeof EditPoliciesEditBeneficiariesRoute
  '/edit-policies': typeof EditPoliciesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/edit-policies/edit-beneficiaries': typeof EditPoliciesEditBeneficiariesRoute
  '/edit-policies/': typeof EditPoliciesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/edit-policies/edit-beneficiaries'
    | '/edit-policies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/edit-policies/edit-beneficiaries' | '/edit-policies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/edit-policies/edit-beneficiaries'
    | '/edit-policies/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EditPoliciesEditBeneficiariesRoute: typeof EditPoliciesEditBeneficiariesRoute
  EditPoliciesIndexRoute: typeof EditPoliciesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EditPoliciesEditBeneficiariesRoute: EditPoliciesEditBeneficiariesRoute,
  EditPoliciesIndexRoute: EditPoliciesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/edit-policies/edit-beneficiaries",
        "/edit-policies/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/edit-policies/edit-beneficiaries": {
      "filePath": "edit-policies/edit-beneficiaries.tsx"
    },
    "/edit-policies/": {
      "filePath": "edit-policies/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
